services:
  odido-bundle-replenisher:
    image: ghcr.io/lodu/odido-bundle-replenisher:main
    restart: unless-stopped
    pull_policy: always
    env_file:
      - .env
    # environment:
    #   - MSISDN=
    #   - AUTHORIZATION_TOKEN=
