services:
  odido-bundle-replenisher:
    image: ghcr.io/lodu/odido-bundle-replenisher:latest
    restart: unless-stopped
    pull_policy: always
    tty: true
    stdin_open: true
    env_file:
      - .env
    # environment:
    #   - MSISDN=
    #   - AUTHORIZATION_TOKEN=
